apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: cpu-pod-scaling-{{component_name}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{component_name}}
  minReplicas: 3
  maxReplicas: 110
  metrics:
    - type: Resource
      resource:
       name: memory
       targetAverageValue: 500Mi
      resource:
        name: cpu
        targetAverageUtilization: 60
