# Master Skaffold
apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: backends
requires:
- path: ./common
  configs: [common]
  activeProfiles: &dev_and_custom_backends
  - name: custom
    activatedBy: [custom]
  - name: dev
    activatedBy: [dev]

- path: ./microservices/authentication
  configs: [authentication]
  activeProfiles: *dev_and_custom_backends

- path: ./microservices/sample_service
  configs: [sample-service]
  activeProfiles:  *dev_and_custom_backends

profiles:
- name: custom
- name: dev
  activation:
  - kubeContext: gke_solutions-template_us-central1-a_default-cluster
