# Master Skaffold
apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: backends
requires:
- path: ./common
  configs: [common]

- path: ./microservices/sample_service
  configs: [sample-service]
