# Master Skaffold
apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: backends
requires:
- configs:
  - common
  path: ./common
- configs:
  - sample-service
  path: ./microservices/sample_service
- configs:
  - frontend-angular
  path: ./microservices/frontend_angular
