apiVersion: v1
kind: Service
metadata:
  name: frontend-angular
  labels:
    app: frontend-angular
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend-angular