name: Auth and setup Cloud SDK with Service Account

on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  gcloud_setup:
    runs-on: ubuntu-latest
    steps:
    # https://github.com/google-github-actions/auth
    - id: 'auth'
      name: Auth with Service Account
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        # FIXME: Use workload identity instead of service account key.
        # workload_identity_provider: ''
        # service_account: 'deployment-dev@${{ env.PROJECT_ID }}.iam.gserviceaccount.com'

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v1'
