apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{resource_name}}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: gke-ingress-ip
    networking.gke.io/managed-certificates: default-managed-cert
    networking.gke.io/v1beta1.FrontendConfig: default-frontend-config
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - http:
        paths: {% for service_name in kubernetes_services.split(",") %}
          - path: /{{service_name}}/
            pathType: Prefix
            backend:
              service:
                name: {{service_name}}
                port:
                  number: 80
          {% endfor %}
