apiVersion: v1
kind: Service
metadata:
  name: authentication
  labels:
    app: authentication
spec:
  type: NodePort
  ports:
  - port: 8889
    protocol: TCP
    targetPort: 8889
  selector:
    app: authentication