apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-service
  template:
    metadata:
      labels:
        app: sample-service
    spec:
      containers:
      - name: sample-service
        image: sample-service
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "250m"
            memory: "100Mi"
          limits:
            memory: "5000Mi"
            cpu: "2000m"
        env:
        # Define the environment variable
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: config-port-config
              key: sample-service.PORT
        - name: GCP_PROJECT
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: GCP_PROJECT
        ports:
        - containerPort: 8888
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /ping
            port: 8888
            scheme: HTTP
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /ping
            port: 8888
            scheme: HTTP
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10