apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: frontend-angular
spec:
  template:
    spec:
      containers:
      - name: frontend-angular
        image: frontend-angular
        ports:
          - containerPort: 80
