project_id          = "{{project_id}}"
project_number      = "{{project_number}}"
region              = "{{gcp_region}}"
firestore_region    = "{{gcp_region}}"
storage_multiregion = "US"
cors_allow_origins  = "{{cors_allow_origins}}"
cert_issuer_email   = "{{cert_issuer_email}}"
kubernetes_version  = "{{kubernetes_version}}"
