apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: {{component_name}}

{% if depend_on_common == true -%}
# Requires the common image for shared data models or utils.
requires:
- configs:
  - common
  path: ../common
{%- endif %}

build:
  artifacts:
  - image: {{component_name}}
    sync:
      infer:
      - '**/*.py'
      - '**/*.json'
    docker:
      cacheFrom:
      - {{component_name}}
      - {{component_name}}:latest
    requires:
    - image: common
      alias: BASE_IMG
  googleCloudBuild: {}

# Portforwarding when running `skaffold dev` locally.
portForward:
- resourceType: service
  resourceName: {{component_name}}
  port: 80
  localPort: 9001 # Change this when adding other microservice.

profiles:
# Profile for building images locally.
- name: local_build
  build:
    artifacts:
    - image: {{component_name}}
      requires:
      - image: common
        alias: BASE_IMG
      sync:
        infer:
        - '**/*.py'
        - '**/*.json'
    tagPolicy:
      gitCommit: {}
    local:
      concurrency: 0

{% if deploy_gke == true -%}
# Profile for GKE deployment, building images via CloudBuild
- &gke-profile # YAML anchor used by "default" profile.
  name: gke
  manifests:
    # Loading kustomize base file for deployment.
    kustomize:
      paths:
      - ./kustomize/base
    # Substitute system's environment vars to properties.rendered.env
    hooks:
      before:
      - host:
          dir: ./kustomize/base
          command: ["sh", "-c",
            "envsubst < properties.env > properties.rendered.env"]
      after:
      - host:
          dir: ./kustomize/base
          command: ["sh", "-c", "rm *.rendered.env"]
  # Simple deployment using kubectl.
  deploy:
    kubectl: {}

# Profile for GKE Horizontal Pod Autoscaler.
# This profile only works with `gke` profile together.
# E.g. skaffold run -p gke,hpa
- name: gke-hpa
  manifests:
    kustomize:
      paths:
      - ./kustomize/hpa
  # Simple deployment using kubectl.
  deploy:
    kubectl: {}
{%- endif %}

{% if deploy_cloudrun == true -%}
# Profile for Cloud Run deployment, building images via CloudBuild
- &cloudrun-profile # YAML anchor used by "default" profile.
  name: cloudrun
  manifests:
    rawYaml:
      - manifests/cloudrun-service.yaml
  deploy:
    cloudrun:
      projectid: {{project_id}}
      region: {{gcp_region}}
  portForward:
  - resourceType: service
    resourceName: {{cloudrun_resource_name}}
    port: 80
    localPort: 9001 # Change this when adding other microservice.
{%- endif %}

{% if default_deploy == "cloudrun" -%}
- <<: *cloudrun-profile
  name: default
{%- endif %}
