apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-service
spec:
  template:
    spec:
      containers:
      - name: sample-service
        image: sample-service
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "500Mi"