apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sample-service
spec:
  template:
    spec:
      containers:
      - name: sample-service
        image: sample-service
        ports:
          - containerPort: 80