apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: common
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: common
    sync:
      infer:
        - '**/*.py'
        - '**/*.json'

profiles:
- name: custom
- name: dev
  build:
    googleCloudBuild: {}
    artifacts:
    - image: gcr.io/solutions-template/common
      sync:
        infer:
          - '**/*.py'
          - '**/*.json'