apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: common
build:
  artifacts:
  - image: common
    sync:
      infer:
      - '**/*.py'
      - '**/*.json'
  tagPolicy:
    gitCommit: {}
profiles:
- name: custom
  build:
    artifacts:
    - image: common
      docker:
        cacheFrom:
        - common
        - common:latest
    googleCloudBuild: {}
- name: prod
  build:
    artifacts:
    - image: common
      sync:
        infer:
        - '**/*.py'
        - '**/*.json'
      docker:
        cacheFrom:
        - common
        - common:latest
    googleCloudBuild: {}
- name: dev
  activation:
  - kubeContext: gke_solutions-template-e2etest_us-central1_main-cluster
  build:
    artifacts:
    - image: gcr.io/solutions-template-e2etest/common
      sync:
        infer:
        - '**/*.py'
        - '**/*.json'
      docker:
        cacheFrom:
        - gcr.io/solutions-template-e2etest/common
        - gcr.io/solutions-template-e2etest/common:latest
    googleCloudBuild: {}
