apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: common
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: common
    sync:
      infer:
        - '**/*.py'
        - '**/*.json'

profiles:
- name: custom
  build:
    googleCloudBuild: {}
    artifacts:
    - image: common
      docker:
        cacheFrom:
          - common
          - common:latest
- name: prod
  build:
    googleCloudBuild: {}
    artifacts:
    - image: common
      docker:
        cacheFrom:
          - common
          - common:latest
      sync:
        infer:
          - '**/*.py'
          - '**/*.json'
- name: prod_non_cloudbuild
- name: dev
  activation:
  - kubeContext: gke_solutions-template-dev_us-central1-a_default-cluster
  build:
    googleCloudBuild: {}
    artifacts:
    - image: gcr.io/solutions-template-dev/common
      docker:
        cacheFrom:
          - gcr.io/solutions-template-dev/common
          - gcr.io/solutions-template-dev/common:latest
      sync:
        infer:
          - '**/*.py'
          - '**/*.json'