apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-service
spec:
  replicas: 3
  template:
    spec:
      serviceAccountName: gke-sa
      containers:
      - name: sample-service
        image: sample-service
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "250m"
            memory: "100Mi"
          limits:
            memory: "5000Mi"
            cpu: "2000m"
        env:
        - name: PROJECT_ID
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: PROJECT_ID
        - name: DATABASE_PREFIX
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: DATABASE_PREFIX
