apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-service
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: sample-service
        image: sample-service
        imagePullPolicy: Always
        env:
        - name: GCP_PROJECT
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: GCP_PROJECT
        - name: EXTERNAL_DATA_GCP_PROJECT
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: EXTERNAL_DATA_GCP_PROJECT
