apiVersion: v1
kind: Service
metadata:
  name: {{resource_name}}
  labels:
    app: {{resource_name}}
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: {{resource_name}}
