# Build this service to Artifact Registry and deploy to CloudRun as a service.

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--build-arg'
      - 'BASE_IMG=${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/common'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:latest'
      - '--cache-from'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:latest'
      - '-f'
      - Dockerfile
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE}'

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - '${_CLOUD_RUN_SERVICE_NAME}'
      - '--service-account'
      - '${_SERVICE_ACCOUNT}'
      - '--project'
      - '${_PROJECT_ID}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE}'
      - '--region'
      - '${_REGION}'
      - '${_ALLOW_UNAUTHENTICATED_FLAG}'
