apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: sample-service
requires:
  - path: ../../common
    configs: [common]
build:
  tagPolicy:
    gitCommit: {}
  local:
    concurrency: 0
  artifacts:
  - image: sample-service
    requires:
      - image: common
        alias: BASE_IMG
    sync:
      infer:
        - '**/*.py'
        - '**/*.json'
portForward:
- resourceType: service
  resourceName: sample-service
  port: 80
  localPort: 8888
deploy:
  kustomize:
    paths:
    - ./kustomize/minikube
profiles:
- name: custom
  build:
    googleCloudBuild: {}
    artifacts:
    - image: sample-service
      requires:
      - image: common
        alias: BASE_IMG
  deploy:
    kustomize:
      paths:
      - ./kustomize/custom
- name: prod_non_cloudbuild
  deploy:
    kustomize:
      paths:
      - ./kustomize/prod
- name: prod
  deploy:
    kustomize:
      paths:
      - ./kustomize/prod
  build:
    googleCloudBuild: {}
    artifacts:
    - image: sample-service
      docker:
        cacheFrom:
          - sample-service
          - sample-service:latest
      requires:
      - image: common
        alias: BASE_IMG
- name: dev
  activation:
  - kubeContext: gke_{{cookiecutter.project_id}}_{{cookiecutter.gcp_region}}_default-cluster
  build:
    googleCloudBuild: {}
    artifacts:
    - image: gcr.io/{{cookiecutter.project_id}}/sample-service
      docker:
        cacheFrom:
          - gcr.io/{{cookiecutter.project_id}}/sample-service
          - gcr.io/{{cookiecutter.project_id}}/sample-service:latest
      requires:
        - image: gcr.io/{{cookiecutter.project_id}}/common
          alias: BASE_IMG
      sync:
        infer:
          - '**/*.py'
          - '**/*.json'
  deploy:
    kustomize:
      paths:
      - ./kustomize/dev