apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: sample-service

# Requires the common image for shared data models or utils.
requires:
- configs:
  - common
  path: ../../common

build:
  artifacts:
  - image: sample-service
    requires:
    - image: common
      alias: BASE_IMG
    docker:
      cacheFrom:
      - sample-service
      - sample-service:latest
  googleCloudBuild: {}

# Portforwarding when running `skaffold dev` locally.
portForward:
- resourceType: service
  resourceName: sample-service
  port: 80
  localPort: 9001 # Change this when adding other microservice.

profiles:
# Profile for building images locally.
- name: local_build
  build:
    artifacts:
    - image: sample-service
      requires:
      - image: common
        alias: BASE_IMG
      sync:
        infer:
        - '**/*.py'
        - '**/*.json'
    tagPolicy:
      gitCommit: {}
    local:
      concurrency: 0

# Profile for GKE deployment, building images via CloudBuild
- name: gke
  build:
    artifacts:
    - image: sample-service
      sync:
        infer:
        - '**/*.py'
        - '**/*.json'
      docker:
        cacheFrom:
        - sample-service
        - sample-service:latest
      requires:
      - image: common
        alias: BASE_IMG
    googleCloudBuild: {}
  manifests:
    # Loading kustomzie base file for deployment.
    kustomize:
      paths:
      - ./kustomize/base
    # Substitute system's environment vars to properties.rendered.env
    hooks:
      before:
      - host:
          dir: ./kustomize/base
          command: ["sh", "-c",
            "envsubst < properties.env > properties.rendered.env"]
      after:
      - host:
          dir: ./kustomize/base
          command: ["sh", "-c", "rm *.rendered.env"]

  # Simple deployment using kubectl.
  deploy:
    kubectl: {}

# Profile for GKE Horizontal Pod Autoscaler.
# This profile only works with `gke` profile together.
# E.g. skaffold run -p gke,hpa
- name: hpa
  manifests:
    kustomize:
      paths:
      - ./kustomize/hpa

# Profile for Dev environment, building images via CloudBuild
- name: cloudrun
  manifests:
    rawYaml:
      - cloudrun_manifests/*
  deploy:
    cloudrun:
      region: {{cookiecutter.gcp_region}}
  portForward:
  - resourceType: service
    resourceName: sample-service
    port: 80
    localPort: 9001 # Change this when adding other microservice.
