apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: sample-service

# Requires the common image for shared data models or utils.
requires:
- configs:
  - common
  path: ../../common
build:
  artifacts:
  - image: sample-service
    requires:
    - image: common
      alias: BASE_IMG
    sync:
      infer:
      - '**/*.py'
      - '**/*.json'
  tagPolicy:
    gitCommit: {}
  local:
    concurrency: 0
manifests:
  kustomize:
    paths:
    - ./kustomize/minikube

# Portforwarding when running `skaffold dev` locally.
portForward:
- resourceType: service
  resourceName: sample-service
  port: 80
  localPort: 8001 # Change this when adding other microservice.

# Simple deployment using kubectl.
deploy:
  kubectl: {}

profiles:
# Profile for building images locally.
- name: non_cloudbuild
  manifests:
    kustomize:
      paths:
      - ./kustomize/prod

# Profile for Production environment, building images via CloudBuild.
- name: prod
  build:
    artifacts:
    - image: sample-service
      requires:
      - image: common
        alias: BASE_IMG
      docker:
        cacheFrom:
        - sample-service
        - sample-service:latest
    googleCloudBuild: {}
  manifests:
    kustomize:
      paths:
      - ./kustomize/prod

# Profile for Dev environment, building images via CloudBuild
- name: dev
  build:
    artifacts:
    - image: sample-service
      sync:
        infer:
        - '**/*.py'
        - '**/*.json'
      docker:
        cacheFrom:
        - sample-service
        - sample-service:latest
      requires:
      - image: common
        alias: BASE_IMG
    googleCloudBuild: {}
  manifests:
    kustomize:
      paths:
      - ./kustomize/dev
