_src_path: /Users/jonchen/workspace/solutions-builder/solutions_builder/cli/../template_root
advanced_settings: false
create_vpc_network: true
folder_name: simple_restful_apis
gcp_region: us-central1
has_common: true
ip_cidr_range: 10.0.0.0/16
jump_host_zone: us-central1-a
master_ipv4_cidr_block: 172.16.0.0/28
project_id: your-project-id
project_name: simple_restful_apis
project_number: 561278228515
secondary_pod_ip_cidr_range: 10.1.0.0/16
secondary_service_ip_cidr_range: 10.2.0.0/16
terraform_backend_gcs: true
use_jump_host: true
vpc_network: default-vpc
vpc_subnetwork: default-vpc-subset
