apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: authentication
build:
  tagPolicy:
    sha256: {}
  local:
    concurrency: 1
  artifacts:
  - image: authentication
    sync:
      infer:
        - '**/*.py'
        - '**/*.json'
portForward:
- resourceType: service
  resourceName: authentication
  port: 8889
deploy:
  kustomize:
    paths:
    - ./kustomize/minikube
profiles:
- name: custom
  deploy:
    kustomize:
      paths:
      - ./kustomize/custom
- name: dev
  build:
    googleCloudBuild: {}
    artifacts:
    - image: gcr.io/solutions-template/authentication
      sync:
        infer:
          - '**/*.py'
          - '**/*.json'
  deploy:
    kustomize:
      paths:
      - ./kustomize/dev
