apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
spec:
  template:
    spec:
      containers:
      - name: authentication
        image: authentication
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "500Mi"
