# changed from slim for FireO
FROM python:3.7-slim

WORKDIR /opt

# needed for backports-datetime-fromisoformat in fireo
RUN apt-get update
RUN apt-get -y install gcc

COPY requirements.txt .
COPY requirements-test.txt .

RUN pip install -r requirements.txt
RUN pip install -r requirements-test.txt

COPY src/ .

CMD PYTEST_ADDOPTS="--cache-clear --cov . " PYTHONPATH=common/src python -m pytest
