apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: common
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: common
    sync:
      infer:
        - '**/*.py'
        - '**/*.json'

profiles:
- name: custom
  build:
    googleCloudBuild: {}
    artifacts:
    - image: common
      docker:
        cacheFrom:
          - common
          - common:latest
- name: prod
  build:
    googleCloudBuild: {}
    artifacts:
    - image: common
      docker:
        cacheFrom:
          - common
          - common:latest
      sync:
        infer:
          - '**/*.py'
          - '**/*.json'
- name: dev
  activation:
  - kubeContext: gke_{{cookiecutter.project_id}}_{{cookiecutter.gcp_region}}_default-cluster
  build:
    googleCloudBuild: {}
    artifacts:
    - image: gcr.io/{{cookiecutter.project_id}}/common
      docker:
        cacheFrom:
          - gcr.io/{{cookiecutter.project_id}}/common
          - gcr.io/{{cookiecutter.project_id}}/common:latest
      sync:
        infer:
          - '**/*.py'
          - '**/*.json'