apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: common
build:
  artifacts:
  - image: common
    sync:
      infer:
      - '**/*.py'
      - '**/*.json'
  tagPolicy:
    gitCommit: {}
profiles:
- name: prod
  build:
    artifacts:
    - image: common
      sync:
        infer:
        - '**/*.py'
        - '**/*.json'
      docker:
        cacheFrom:
        - common
        - common:latest
    googleCloudBuild: {}
- name: dev
  activation:
  - kubeContext: gke_{{cookiecutter.project_id}}_{{cookiecutter.gcp_region}}_main-cluster
  build:
    artifacts:
    - image: gcr.io/{{cookiecutter.project_id}}/common
      sync:
        infer:
        - '**/*.py'
        - '**/*.json'
      docker:
        cacheFrom:
        - gcr.io/{{cookiecutter.project_id}}/common
        - gcr.io/{{cookiecutter.project_id}}/common:latest
    googleCloudBuild: {}
