apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: frontend-angular

# Build locally using Buildkit: https://docs.docker.com/build/buildkit
build:
  local:
    useBuildkit: true
  artifacts:
  - image: frontend-angular
    docker:
      cacheFrom:
      - frontend-angular
      - frontend-angular:latest
    sync:
      infer:
      - '**/*.py'
      - '**/*.json'
      - '**/*.js'
      - '**/*.ts'
      - '**/*.sh'
portForward:
- resourceType: service
  resourceName: frontend-angular
  port: 80
  localPort: 8080

profiles:
- name: gke
  manifests:
    kustomize:
      paths:
      - ./kustomize/base
  # Simple deployment using kubectl.
  deploy:
    kubectl: {}
  # Portforwarding when running `skaffold dev` locally.

- name: cloudrun
  manifests:
    rawYaml:
      - manifests/*
  deploy:
    cloudrun:
      projectid: solutions-template-develop
      region: {{cookiecutter.gcp_region}}
