apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-service
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: ksa
      containers:
      - name: sample-service
        image: gcr.io/{{cookiecutter.project_id}}/sample-service
        imagePullPolicy: Always
        env:
        - name: PROJECT_ID
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: PROJECT_ID
        - name: EXTERNAL_DATA_PROJECT_ID
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: EXTERNAL_DATA_PROJECT_ID
        - name: DATABASE_PREFIX
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: DATABASE_PREFIX