apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
patchesStrategicMerge:
- deployment-dev.yaml
configMapGenerator:
- name: env-vars
  behavior: merge
  envs:
  - env.properties
