# This workflow will run Terraform init, validate, and plan on Pull Request=
name: Template E2E test
on:
  issue_comment:
    types: [created]
  workflow_dispatch:

env:
  PROJECT_ID: solutions-template-e2etest
  ORGANIZATION_ID: ${{ secrets.ORGANIZATION_ID }}
  BILLING_ACCOUNT: ${{ secrets.BILLING_ACCOUNT }}
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.E2E_TEST_SA_KEY }}
  KUSTOMIZE_VERSION: 4.1.3
  SKAFFOLD_VERSION: 2.1.0

jobs:
  run_template_e2e_test:
    if: ${{ (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/e2e-test')) || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    environment: e2e
    name: Template E2E tests
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Install gcloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{env.PROJECT_ID}}
        credentials_json: ${{ secrets.E2E_TEST_SA_KEY }}
        export_default_credentials: true

    - name: Install Kustomize
      run: |
        wget -O kustomize.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v$KUSTOMIZE_VERSION/kustomize_v${KUSTOMIZE_VERSION}_linux_amd64.tar.gz

    - name: Install Skaffold release binary
      run: |
        curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v$SKAFFOLD_VERSION/skaffold-linux-amd64
        sudo install skaffold /usr/local/bin/skaffold

    - name: Set default repo for Skaffold
      run: |
        skaffold config set default-repo "$SKAFFOLD_DEFAULT_REPO"

    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.7

    # https://github.com/google-github-actions/auth
    - name: Auth with Service Account
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.E2E_TEST_SA_KEY }}'

    - name: Run e2e test script
      run: |
        bash e2e/template_e2e_tests/run_e2e_test.sh
