# This workflow will run Terraform init, validate, and plan on Pull Request=
name: Template E2E test
on:
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  run_template_e2e_test:
    if: ${{ (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/e2e-test')) || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    environment: e2e
    name: Template E2E tests
    steps:

    - name: Check out repository with main branch
      uses: actions/checkout@v3
      if: ${{ github.event_name == 'workflow_dispatch' }}

    - name: Check out repository with Pull Request HEAD
      uses: actions/checkout@v3
      if: ${{ github.event_name == 'issue_comment' && contains(github.event.comment.body, '/comment-test') }}
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Comment
      uses: actions/github-script@v3
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Running Template E2E test on https://github.com/GoogleCloudPlatform/solutions-template/actions/runs/$GITHUB_CONTEXT.run_id'
          })